### ISSUE TITLE
Responses with multiple representations are not handled properly

### ISSUE THREAD

**Issue by anestos** [curityio/android-haapi-demo-app#6]
Responses with multiple representations, for example the BankID Polling step which contains the BankID autostart URI and a QR code are not triggering the ClientOperationStep. Instead they are used as HaapiRepresentations.

The problem can be identified in the switch in line 101 of FlowActivity.kt

**Comment by gary-archer** [comment]
BankID is the main use case, which has been fixed for same and cross device. The fix is not generic for all other multi-representation use cases, yet we can open more tickets in future if needed, and base fixes on the BankID solution.
